// Vendored verbatim (field names, numbers and types) from Tari's
// `tari/base_layer/core/src/base_node/proto/chain_metadata.proto`
// (github.com/tari-project/tari, `development` branch), as transcribed in
// p2p/RPC_TOR_SPEC.md section A3. Package name and message shapes are exact; only the
// go_package option below is specific to this repo's generated-code layout.
//
// Note: the real upstream file also has an unused `import "google/protobuf/wrappers.proto";`
// with no actual wrapper-typed field left in the message body -- that import is omitted here
// since it's dead in the real file too (every field below is a plain scalar/bytes type).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: p2p/proto/chain_metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainMetadata struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	BestBlockHeight           uint64                 `protobuf:"varint,1,opt,name=best_block_height,json=bestBlockHeight,proto3" json:"best_block_height,omitempty"`
	BestBlockHash             []byte                 `protobuf:"bytes,2,opt,name=best_block_hash,json=bestBlockHash,proto3" json:"best_block_hash,omitempty"`
	AccumulatedDifficultyLow  []byte                 `protobuf:"bytes,5,opt,name=accumulated_difficulty_low,json=accumulatedDifficultyLow,proto3" json:"accumulated_difficulty_low,omitempty"`
	AccumulatedDifficultyHigh []byte                 `protobuf:"bytes,8,opt,name=accumulated_difficulty_high,json=accumulatedDifficultyHigh,proto3" json:"accumulated_difficulty_high,omitempty"`
	PrunedHeight              uint64                 `protobuf:"varint,6,opt,name=pruned_height,json=prunedHeight,proto3" json:"pruned_height,omitempty"`
	Timestamp                 uint64                 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ChainMetadata) Reset() {
	*x = ChainMetadata{}
	mi := &file_p2p_proto_chain_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMetadata) ProtoMessage() {}

func (x *ChainMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_chain_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMetadata.ProtoReflect.Descriptor instead.
func (*ChainMetadata) Descriptor() ([]byte, []int) {
	return file_p2p_proto_chain_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *ChainMetadata) GetBestBlockHeight() uint64 {
	if x != nil {
		return x.BestBlockHeight
	}
	return 0
}

func (x *ChainMetadata) GetBestBlockHash() []byte {
	if x != nil {
		return x.BestBlockHash
	}
	return nil
}

func (x *ChainMetadata) GetAccumulatedDifficultyLow() []byte {
	if x != nil {
		return x.AccumulatedDifficultyLow
	}
	return nil
}

func (x *ChainMetadata) GetAccumulatedDifficultyHigh() []byte {
	if x != nil {
		return x.AccumulatedDifficultyHigh
	}
	return nil
}

func (x *ChainMetadata) GetPrunedHeight() uint64 {
	if x != nil {
		return x.PrunedHeight
	}
	return 0
}

func (x *ChainMetadata) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_p2p_proto_chain_metadata_proto protoreflect.FileDescriptor

const file_p2p_proto_chain_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1ep2p/proto/chain_metadata.proto\x12\x0etari.base_node\"\xa4\x02\n" +
	"\rChainMetadata\x12*\n" +
	"\x11best_block_height\x18\x01 \x01(\x04R\x0fbestBlockHeight\x12&\n" +
	"\x0fbest_block_hash\x18\x02 \x01(\fR\rbestBlockHash\x12<\n" +
	"\x1aaccumulated_difficulty_low\x18\x05 \x01(\fR\x18accumulatedDifficultyLow\x12>\n" +
	"\x1baccumulated_difficulty_high\x18\b \x01(\fR\x19accumulatedDifficultyHigh\x12#\n" +
	"\rpruned_height\x18\x06 \x01(\x04R\fprunedHeight\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x04R\ttimestampB*Z(github.com/Snipa22/go-tari-lib/p2p/protob\x06proto3"

var (
	file_p2p_proto_chain_metadata_proto_rawDescOnce sync.Once
	file_p2p_proto_chain_metadata_proto_rawDescData []byte
)

func file_p2p_proto_chain_metadata_proto_rawDescGZIP() []byte {
	file_p2p_proto_chain_metadata_proto_rawDescOnce.Do(func() {
		file_p2p_proto_chain_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_chain_metadata_proto_rawDesc), len(file_p2p_proto_chain_metadata_proto_rawDesc)))
	})
	return file_p2p_proto_chain_metadata_proto_rawDescData
}

var file_p2p_proto_chain_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_p2p_proto_chain_metadata_proto_goTypes = []any{
	(*ChainMetadata)(nil), // 0: tari.base_node.ChainMetadata
}
var file_p2p_proto_chain_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p2p_proto_chain_metadata_proto_init() }
func file_p2p_proto_chain_metadata_proto_init() {
	if File_p2p_proto_chain_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_chain_metadata_proto_rawDesc), len(file_p2p_proto_chain_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_chain_metadata_proto_goTypes,
		DependencyIndexes: file_p2p_proto_chain_metadata_proto_depIdxs,
		MessageInfos:      file_p2p_proto_chain_metadata_proto_msgTypes,
	}.Build()
	File_p2p_proto_chain_metadata_proto = out.File
	file_p2p_proto_chain_metadata_proto_goTypes = nil
	file_p2p_proto_chain_metadata_proto_depIdxs = nil
}
