// Vendored verbatim (field names, numbers and types) from Tari's
// `tari/comms/dht/src/proto/rpc.proto` (github.com/tari-project/tari, `development` branch), as
// transcribed for the `t/dht/1` `get_peers` streaming RPC (source: `comms/dht/src/rpc/mod.rs`).
// Package name and message shapes are exact; only the go_package option below is specific to
// this repo's generated-code layout.
//
// Deliberate deviation from the real Rust source (documented, not an oversight): the real Tari
// source has a SEPARATE `comms/dht/src/proto/common.proto`, package `tari.dht.common`, with an
// `IdentitySignature` message that is structurally identical to the one already vendored in
// p2p/proto/identity.proto (package `tari.comms.identity`, message `IdentitySignature`: fields
// version=1 uint32, signature=2 bytes, public_nonce=3 bytes, updated_at=4 int64). Rather than
// vendoring a byte-identical duplicate proto message under a different package purely to mirror
// Rust's package boundary, this file directly imports and reuses
// `tari.comms.identity.IdentitySignature` from p2p/proto/identity.proto. On the wire, protobuf
// field encoding doesn't care about a message type's "name" or declaring package, only its
// field numbers/types/shape, which are identical here -- so this substitution has no behavioral
// effect on the wire format; it only avoids pure boilerplate duplication in this Go port. See
// p2p/VERIFICATION.md's "Part E addendum" for further discussion.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: p2p/proto/dht_rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeersRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	N                    uint32                 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	IncludeClients       bool                   `protobuf:"varint,2,opt,name=include_clients,json=includeClients,proto3" json:"include_clients,omitempty"`
	MaxClaims            uint32                 `protobuf:"varint,3,opt,name=max_claims,json=maxClaims,proto3" json:"max_claims,omitempty"`
	MaxAddressesPerClaim uint32                 `protobuf:"varint,4,opt,name=max_addresses_per_claim,json=maxAddressesPerClaim,proto3" json:"max_addresses_per_claim,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_dht_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetPeersRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GetPeersRequest) GetIncludeClients() bool {
	if x != nil {
		return x.IncludeClients
	}
	return false
}

func (x *GetPeersRequest) GetMaxClaims() uint32 {
	if x != nil {
		return x.MaxClaims
	}
	return 0
}

func (x *GetPeersRequest) GetMaxAddressesPerClaim() uint32 {
	if x != nil {
		return x.MaxAddressesPerClaim
	}
	return 0
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_dht_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeersResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Claims        []*PeerIdentityClaim   `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_p2p_proto_dht_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerInfo) GetClaims() []*PeerIdentityClaim {
	if x != nil {
		return x.Claims
	}
	return nil
}

type PeerIdentityClaim struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Addresses    [][]byte               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PeerFeatures uint32                 `protobuf:"varint,2,opt,name=peer_features,json=peerFeatures,proto3" json:"peer_features,omitempty"`
	// See the file-level doc comment above: real Tari declares this field as
	// `tari.dht.common.IdentitySignature`, a byte-identical sibling message in a separate proto
	// package this Go port does not vendor a duplicate of.
	IdentitySignature *IdentitySignature `protobuf:"bytes,3,opt,name=identity_signature,json=identitySignature,proto3" json:"identity_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PeerIdentityClaim) Reset() {
	*x = PeerIdentityClaim{}
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerIdentityClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerIdentityClaim) ProtoMessage() {}

func (x *PeerIdentityClaim) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_dht_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerIdentityClaim.ProtoReflect.Descriptor instead.
func (*PeerIdentityClaim) Descriptor() ([]byte, []int) {
	return file_p2p_proto_dht_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PeerIdentityClaim) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerIdentityClaim) GetPeerFeatures() uint32 {
	if x != nil {
		return x.PeerFeatures
	}
	return 0
}

func (x *PeerIdentityClaim) GetIdentitySignature() *IdentitySignature {
	if x != nil {
		return x.IdentitySignature
	}
	return nil
}

var File_p2p_proto_dht_rpc_proto protoreflect.FileDescriptor

const file_p2p_proto_dht_rpc_proto_rawDesc = "" +
	"\n" +
	"\x17p2p/proto/dht_rpc.proto\x12\ftari.dht.rpc\x1a\x18p2p/proto/identity.proto\"\x9e\x01\n" +
	"\x0fGetPeersRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\x12'\n" +
	"\x0finclude_clients\x18\x02 \x01(\bR\x0eincludeClients\x12\x1d\n" +
	"\n" +
	"max_claims\x18\x03 \x01(\rR\tmaxClaims\x125\n" +
	"\x17max_addresses_per_claim\x18\x04 \x01(\rR\x14maxAddressesPerClaim\">\n" +
	"\x10GetPeersResponse\x12*\n" +
	"\x04peer\x18\x01 \x01(\v2\x16.tari.dht.rpc.PeerInfoR\x04peer\"b\n" +
	"\bPeerInfo\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x127\n" +
	"\x06claims\x18\x02 \x03(\v2\x1f.tari.dht.rpc.PeerIdentityClaimR\x06claims\"\xad\x01\n" +
	"\x11PeerIdentityClaim\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\fR\taddresses\x12#\n" +
	"\rpeer_features\x18\x02 \x01(\rR\fpeerFeatures\x12U\n" +
	"\x12identity_signature\x18\x03 \x01(\v2&.tari.comms.identity.IdentitySignatureR\x11identitySignatureB*Z(github.com/Snipa22/go-tari-lib/p2p/protob\x06proto3"

var (
	file_p2p_proto_dht_rpc_proto_rawDescOnce sync.Once
	file_p2p_proto_dht_rpc_proto_rawDescData []byte
)

func file_p2p_proto_dht_rpc_proto_rawDescGZIP() []byte {
	file_p2p_proto_dht_rpc_proto_rawDescOnce.Do(func() {
		file_p2p_proto_dht_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_dht_rpc_proto_rawDesc), len(file_p2p_proto_dht_rpc_proto_rawDesc)))
	})
	return file_p2p_proto_dht_rpc_proto_rawDescData
}

var file_p2p_proto_dht_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_p2p_proto_dht_rpc_proto_goTypes = []any{
	(*GetPeersRequest)(nil),   // 0: tari.dht.rpc.GetPeersRequest
	(*GetPeersResponse)(nil),  // 1: tari.dht.rpc.GetPeersResponse
	(*PeerInfo)(nil),          // 2: tari.dht.rpc.PeerInfo
	(*PeerIdentityClaim)(nil), // 3: tari.dht.rpc.PeerIdentityClaim
	(*IdentitySignature)(nil), // 4: tari.comms.identity.IdentitySignature
}
var file_p2p_proto_dht_rpc_proto_depIdxs = []int32{
	2, // 0: tari.dht.rpc.GetPeersResponse.peer:type_name -> tari.dht.rpc.PeerInfo
	3, // 1: tari.dht.rpc.PeerInfo.claims:type_name -> tari.dht.rpc.PeerIdentityClaim
	4, // 2: tari.dht.rpc.PeerIdentityClaim.identity_signature:type_name -> tari.comms.identity.IdentitySignature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_p2p_proto_dht_rpc_proto_init() }
func file_p2p_proto_dht_rpc_proto_init() {
	if File_p2p_proto_dht_rpc_proto != nil {
		return
	}
	file_p2p_proto_identity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_dht_rpc_proto_rawDesc), len(file_p2p_proto_dht_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_dht_rpc_proto_goTypes,
		DependencyIndexes: file_p2p_proto_dht_rpc_proto_depIdxs,
		MessageInfos:      file_p2p_proto_dht_rpc_proto_msgTypes,
	}.Build()
	File_p2p_proto_dht_rpc_proto = out.File
	file_p2p_proto_dht_rpc_proto_goTypes = nil
	file_p2p_proto_dht_rpc_proto_depIdxs = nil
}
