// Vendored verbatim (field names, numbers and types) from Tari's
// `tari/comms/core/src/proto/identity.proto` (github.com/tari-project/tari, `development`
// branch), as transcribed in P2P_SPEC.md section 6. Package name and message shapes are exact;
// only the go_package option below is specific to this repo's generated-code layout.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerIdentityMsg struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Addresses          [][]byte               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Features           uint32                 `protobuf:"varint,2,opt,name=features,proto3" json:"features,omitempty"`
	SupportedProtocols [][]byte               `protobuf:"bytes,3,rep,name=supported_protocols,json=supportedProtocols,proto3" json:"supported_protocols,omitempty"`
	UserAgent          string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IdentitySignature  *IdentitySignature     `protobuf:"bytes,5,opt,name=identity_signature,json=identitySignature,proto3" json:"identity_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PeerIdentityMsg) Reset() {
	*x = PeerIdentityMsg{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerIdentityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerIdentityMsg) ProtoMessage() {}

func (x *PeerIdentityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerIdentityMsg.ProtoReflect.Descriptor instead.
func (*PeerIdentityMsg) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *PeerIdentityMsg) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerIdentityMsg) GetFeatures() uint32 {
	if x != nil {
		return x.Features
	}
	return 0
}

func (x *PeerIdentityMsg) GetSupportedProtocols() [][]byte {
	if x != nil {
		return x.SupportedProtocols
	}
	return nil
}

func (x *PeerIdentityMsg) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *PeerIdentityMsg) GetIdentitySignature() *IdentitySignature {
	if x != nil {
		return x.IdentitySignature
	}
	return nil
}

type IdentitySignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicNonce   []byte                 `protobuf:"bytes,3,opt,name=public_nonce,json=publicNonce,proto3" json:"public_nonce,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySignature) Reset() {
	*x = IdentitySignature{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySignature) ProtoMessage() {}

func (x *IdentitySignature) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySignature.ProtoReflect.Descriptor instead.
func (*IdentitySignature) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentitySignature) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IdentitySignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *IdentitySignature) GetPublicNonce() []byte {
	if x != nil {
		return x.PublicNonce
	}
	return nil
}

func (x *IdentitySignature) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\x13tari.comms.identity\"\xf2\x01\n" +
	"\x0fPeerIdentityMsg\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\fR\taddresses\x12\x1a\n" +
	"\bfeatures\x18\x02 \x01(\rR\bfeatures\x12/\n" +
	"\x13supported_protocols\x18\x03 \x03(\fR\x12supportedProtocols\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12U\n" +
	"\x12identity_signature\x18\x05 \x01(\v2&.tari.comms.identity.IdentitySignatureR\x11identitySignature\"\x8d\x01\n" +
	"\x11IdentitySignature\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12!\n" +
	"\fpublic_nonce\x18\x03 \x01(\fR\vpublicNonce\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAtB*Z(github.com/Snipa22/go-tari-lib/p2p/protob\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_proto_goTypes = []any{
	(*PeerIdentityMsg)(nil),   // 0: tari.comms.identity.PeerIdentityMsg
	(*IdentitySignature)(nil), // 1: tari.comms.identity.IdentitySignature
}
var file_identity_proto_depIdxs = []int32{
	1, // 0: tari.comms.identity.PeerIdentityMsg.identity_signature:type_name -> tari.comms.identity.IdentitySignature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
