// Vendored verbatim (field names, numbers and types) from Tari's
// `tari/comms/core/src/proto/rpc.proto` (github.com/tari-project/tari, `development` branch),
// as transcribed in p2p/RPC_TOR_SPEC.md section A2. Package name and message shapes are exact;
// only the go_package option below is specific to this repo's generated-code layout.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.1
// source: p2p/proto/rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcSessionReply_HandshakeRejectReason int32

const (
	RpcSessionReply_HANDSHAKE_REJECT_REASON_UNKNOWN                      RpcSessionReply_HandshakeRejectReason = 0
	RpcSessionReply_HANDSHAKE_REJECT_REASON_UNSUPPORTED_VERSION          RpcSessionReply_HandshakeRejectReason = 1
	RpcSessionReply_HANDSHAKE_REJECT_REASON_NO_SERVER_SESSIONS_AVAILABLE RpcSessionReply_HandshakeRejectReason = 2
	RpcSessionReply_HANDSHAKE_REJECT_REASON_NO_CLIENT_SESSIONS_AVAILABLE RpcSessionReply_HandshakeRejectReason = 3
	RpcSessionReply_HANDSHAKE_REJECT_REASON_PROTOCOL_NOT_SUPPORTED       RpcSessionReply_HandshakeRejectReason = 4
)

// Enum value maps for RpcSessionReply_HandshakeRejectReason.
var (
	RpcSessionReply_HandshakeRejectReason_name = map[int32]string{
		0: "HANDSHAKE_REJECT_REASON_UNKNOWN",
		1: "HANDSHAKE_REJECT_REASON_UNSUPPORTED_VERSION",
		2: "HANDSHAKE_REJECT_REASON_NO_SERVER_SESSIONS_AVAILABLE",
		3: "HANDSHAKE_REJECT_REASON_NO_CLIENT_SESSIONS_AVAILABLE",
		4: "HANDSHAKE_REJECT_REASON_PROTOCOL_NOT_SUPPORTED",
	}
	RpcSessionReply_HandshakeRejectReason_value = map[string]int32{
		"HANDSHAKE_REJECT_REASON_UNKNOWN":                      0,
		"HANDSHAKE_REJECT_REASON_UNSUPPORTED_VERSION":          1,
		"HANDSHAKE_REJECT_REASON_NO_SERVER_SESSIONS_AVAILABLE": 2,
		"HANDSHAKE_REJECT_REASON_NO_CLIENT_SESSIONS_AVAILABLE": 3,
		"HANDSHAKE_REJECT_REASON_PROTOCOL_NOT_SUPPORTED":       4,
	}
)

func (x RpcSessionReply_HandshakeRejectReason) Enum() *RpcSessionReply_HandshakeRejectReason {
	p := new(RpcSessionReply_HandshakeRejectReason)
	*p = x
	return p
}

func (x RpcSessionReply_HandshakeRejectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcSessionReply_HandshakeRejectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_p2p_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcSessionReply_HandshakeRejectReason) Type() protoreflect.EnumType {
	return &file_p2p_proto_rpc_proto_enumTypes[0]
}

func (x RpcSessionReply_HandshakeRejectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcSessionReply_HandshakeRejectReason.Descriptor instead.
func (RpcSessionReply_HandshakeRejectReason) EnumDescriptor() ([]byte, []int) {
	return file_p2p_proto_rpc_proto_rawDescGZIP(), []int{3, 0}
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        uint32                 `protobuf:"varint,2,opt,name=method,proto3" json:"method,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Deadline      uint64                 `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Payload       []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_p2p_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RpcRequest) GetMethod() uint32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *RpcRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RpcRequest) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *RpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	Payload       []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_p2p_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RpcResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RpcResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *RpcResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupportedVersions []uint32               `protobuf:"varint,1,rep,packed,name=supported_versions,json=supportedVersions,proto3" json:"supported_versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RpcSession) Reset() {
	*x = RpcSession{}
	mi := &file_p2p_proto_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcSession) ProtoMessage() {}

func (x *RpcSession) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcSession.ProtoReflect.Descriptor instead.
func (*RpcSession) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcSession) GetSupportedVersions() []uint32 {
	if x != nil {
		return x.SupportedVersions
	}
	return nil
}

type RpcSessionReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SessionResult:
	//
	//	*RpcSessionReply_AcceptedVersion
	//	*RpcSessionReply_Rejected
	SessionResult isRpcSessionReply_SessionResult       `protobuf_oneof:"session_result"`
	RejectReason  RpcSessionReply_HandshakeRejectReason `protobuf:"varint,3,opt,name=reject_reason,json=rejectReason,proto3,enum=tari.comms.rpc.RpcSessionReply_HandshakeRejectReason" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcSessionReply) Reset() {
	*x = RpcSessionReply{}
	mi := &file_p2p_proto_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcSessionReply) ProtoMessage() {}

func (x *RpcSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcSessionReply.ProtoReflect.Descriptor instead.
func (*RpcSessionReply) Descriptor() ([]byte, []int) {
	return file_p2p_proto_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RpcSessionReply) GetSessionResult() isRpcSessionReply_SessionResult {
	if x != nil {
		return x.SessionResult
	}
	return nil
}

func (x *RpcSessionReply) GetAcceptedVersion() uint32 {
	if x != nil {
		if x, ok := x.SessionResult.(*RpcSessionReply_AcceptedVersion); ok {
			return x.AcceptedVersion
		}
	}
	return 0
}

func (x *RpcSessionReply) GetRejected() bool {
	if x != nil {
		if x, ok := x.SessionResult.(*RpcSessionReply_Rejected); ok {
			return x.Rejected
		}
	}
	return false
}

func (x *RpcSessionReply) GetRejectReason() RpcSessionReply_HandshakeRejectReason {
	if x != nil {
		return x.RejectReason
	}
	return RpcSessionReply_HANDSHAKE_REJECT_REASON_UNKNOWN
}

type isRpcSessionReply_SessionResult interface {
	isRpcSessionReply_SessionResult()
}

type RpcSessionReply_AcceptedVersion struct {
	AcceptedVersion uint32 `protobuf:"varint,1,opt,name=accepted_version,json=acceptedVersion,proto3,oneof"`
}

type RpcSessionReply_Rejected struct {
	Rejected bool `protobuf:"varint,2,opt,name=rejected,proto3,oneof"`
}

func (*RpcSessionReply_AcceptedVersion) isRpcSessionReply_SessionResult() {}

func (*RpcSessionReply_Rejected) isRpcSessionReply_SessionResult() {}

var File_p2p_proto_rpc_proto protoreflect.FileDescriptor

const file_p2p_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13p2p/proto/rpc.proto\x12\x0etari.comms.rpc\"\x8f\x01\n" +
	"\n" +
	"RpcRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\rR\x06method\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\x04R\bdeadline\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\"t\n" +
	"\vRpcResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\";\n" +
	"\n" +
	"RpcSession\x12-\n" +
	"\x12supported_versions\x18\x01 \x03(\rR\x11supportedVersions\"\xe2\x03\n" +
	"\x0fRpcSessionReply\x12+\n" +
	"\x10accepted_version\x18\x01 \x01(\rH\x00R\x0facceptedVersion\x12\x1c\n" +
	"\brejected\x18\x02 \x01(\bH\x00R\brejected\x12Z\n" +
	"\rreject_reason\x18\x03 \x01(\x0e25.tari.comms.rpc.RpcSessionReply.HandshakeRejectReasonR\frejectReason\"\x95\x02\n" +
	"\x15HandshakeRejectReason\x12#\n" +
	"\x1fHANDSHAKE_REJECT_REASON_UNKNOWN\x10\x00\x12/\n" +
	"+HANDSHAKE_REJECT_REASON_UNSUPPORTED_VERSION\x10\x01\x128\n" +
	"4HANDSHAKE_REJECT_REASON_NO_SERVER_SESSIONS_AVAILABLE\x10\x02\x128\n" +
	"4HANDSHAKE_REJECT_REASON_NO_CLIENT_SESSIONS_AVAILABLE\x10\x03\x122\n" +
	".HANDSHAKE_REJECT_REASON_PROTOCOL_NOT_SUPPORTED\x10\x04B\x10\n" +
	"\x0esession_resultB*Z(github.com/Snipa22/go-tari-lib/p2p/protob\x06proto3"

var (
	file_p2p_proto_rpc_proto_rawDescOnce sync.Once
	file_p2p_proto_rpc_proto_rawDescData []byte
)

func file_p2p_proto_rpc_proto_rawDescGZIP() []byte {
	file_p2p_proto_rpc_proto_rawDescOnce.Do(func() {
		file_p2p_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_proto_rpc_proto_rawDesc), len(file_p2p_proto_rpc_proto_rawDesc)))
	})
	return file_p2p_proto_rpc_proto_rawDescData
}

var file_p2p_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_p2p_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_p2p_proto_rpc_proto_goTypes = []any{
	(RpcSessionReply_HandshakeRejectReason)(0), // 0: tari.comms.rpc.RpcSessionReply.HandshakeRejectReason
	(*RpcRequest)(nil),                         // 1: tari.comms.rpc.RpcRequest
	(*RpcResponse)(nil),                        // 2: tari.comms.rpc.RpcResponse
	(*RpcSession)(nil),                         // 3: tari.comms.rpc.RpcSession
	(*RpcSessionReply)(nil),                    // 4: tari.comms.rpc.RpcSessionReply
}
var file_p2p_proto_rpc_proto_depIdxs = []int32{
	0, // 0: tari.comms.rpc.RpcSessionReply.reject_reason:type_name -> tari.comms.rpc.RpcSessionReply.HandshakeRejectReason
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_p2p_proto_rpc_proto_init() }
func file_p2p_proto_rpc_proto_init() {
	if File_p2p_proto_rpc_proto != nil {
		return
	}
	file_p2p_proto_rpc_proto_msgTypes[3].OneofWrappers = []any{
		(*RpcSessionReply_AcceptedVersion)(nil),
		(*RpcSessionReply_Rejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_proto_rpc_proto_rawDesc), len(file_p2p_proto_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_proto_rpc_proto_goTypes,
		DependencyIndexes: file_p2p_proto_rpc_proto_depIdxs,
		EnumInfos:         file_p2p_proto_rpc_proto_enumTypes,
		MessageInfos:      file_p2p_proto_rpc_proto_msgTypes,
	}.Build()
	File_p2p_proto_rpc_proto = out.File
	file_p2p_proto_rpc_proto_goTypes = nil
	file_p2p_proto_rpc_proto_depIdxs = nil
}
